# Generated by Django 4.0.6 on 2022-12-29 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_client_email_remove_client_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='managers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='email_of_paid_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='login_of_paid_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='password_of_email_paid_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='password_of_paid_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
