# Generated by Django 4.0.6 on 2022-08-05 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlyfans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlyfanstable',
            name='fp',
        ),
        migrations.RemoveField(
            model_name='onlyfanstable',
            name='fp_data',
        ),
        migrations.RemoveField(
            model_name='onlyfanstable',
            name='op',
        ),
        migrations.RemoveField(
            model_name='onlyfanstable',
            name='op_data',
        ),
        migrations.RemoveField(
            model_name='onlyfanstable',
            name='pp',
        ),
        migrations.RemoveField(
            model_name='onlyfanstable',
            name='pp_data',
        ),
        migrations.AddField(
            model_name='onlyfanstable',
            name='table_type',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('data', models.FloatField(null=True)),
                ('data_type', models.TextField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlyfans.onlyfanstable')),
            ],
        ),
    ]
