# Generated by Django 4.0.6 on 2022-12-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyfans', '0002_remove_onlyfanstable_fp_remove_onlyfanstable_fp_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlyfanstable',
            name='date',
            field=models.DateField(default='01-01-2022'),
        ),
    ]
