# Generated by Django 4.0.6 on 2023-01-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anastasiadating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anastasiadatingtable',
            name='table_type',
            field=models.BooleanField(default=False),
        ),
    ]
